services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=attendance
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=viswak123
    container_name: attendance-db
    restart: unless-stopped

  backend:
    image: viswakggautham/attendance-backend:latest
    ports:
      - '8081:8081'
    environment:
      - spring_application_name=attendance-backend
      - spring_datasource_url=jdbc:postgresql://postgres:5432/attendance
      - spring_datasource_username=user
      - spring_datasource_password=viswak123
      - server_port=8081
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: viswakggautham/attendance-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
