CREATE TABLE USERS
(
  UserID INT NOT NULL AUTO_INCREMENT,
  Role VARCHAR(20) NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  SecondName VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE COURSE
(
  CourseID INT NOT NULL AUTO_INCREMENT,
  CourseName VARCHAR(100) NOT NULL,
  Description TEXT,
  PRIMARY KEY (CourseID)
);

CREATE TABLE LECTURE
(
  LectureID INT NOT NULL AUTO_INCREMENT,
  CourseID INT NOT NULL,
  Description TEXT,
  LectureDate DATETIME NOT NULL,
  Attribute VARCHAR(50),
  PRIMARY KEY (LectureID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ENROLLMENTS
(
  UserID INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (UserID, CourseID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ATTENDANCE
(
  UserID INT NOT NULL,
  LectureID INT NOT NULL,
  ScannedAt DATETIME NOT NULL,
  PRIMARY KEY (UserID, LectureID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (LectureID) REFERENCES LECTURE(LectureID) ON DELETE CASCADE ON UPDATE CASCADE
);
