CREATE TABLE USERS
(
  Role VARCHAR(20) NOT NULL,
  UserID INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  SecondName VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE COURSE
(
  CourseID INT NOT NULL,
  CourseName VARCHAR(100) NOT NULL,
  Description TEXT,
  PRIMARY KEY (CourseID)
);

CREATE TABLE LECTURE
(
  LectureID INT NOT NULL,
  Description TEXT,
  LectureDate DATETIME NOT NULL,
  Attribute VARCHAR(50),
  CourseID INT NOT NULL,
  PRIMARY KEY (LectureID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

CREATE TABLE ENROLLMENTS
(
  UserID INT NOT NULL,
  CourseID INT NOT NULL,
  PRIMARY KEY (UserID, CourseID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID),
  FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

CREATE TABLE ATTENDANCE
(
  scanned_at DATETIME NOT NULL,
  UserID INT NOT NULL,
  LectureID INT NOT NULL,
  PRIMARY KEY (UserID, LectureID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID),
  FOREIGN KEY (LectureID) REFERENCES LECTURE(LectureID)
);
